// Preloaded Cinephile deck. Seeded into IndexedDB on first visit;
// after that the database is the source of truth so users can edit freely.
const PRELOADED_CARDS = [
  { num: 1,  actor: 'MATTHEW McCONAUGHEY',        movie: 'Interstellar' },
  { num: 2,  actor: 'BRAD PITT',                  movie: 'Fight Club' },
  { num: 3,  actor: 'BRUCE WILLIS',               movie: 'Die Hard' },
  { num: 4,  actor: 'ADAM SANDLER',               movie: 'Grown Ups' },
  { num: 5,  actor: 'ROBERT DOWNEY JR.',          movie: 'The Avengers (2012)' },
  { num: 6,  actor: 'JACK NICHOLSON',             movie: 'The Shining' },
  { num: 7,  actor: 'TIMOTHÉE CHALAMET',          movie: 'Dune: Part One' },
  { num: 8,  actor: 'CHRIS PRATT',                movie: 'Guardians of the Galaxy' },
  { num: 9,  actor: 'HUGH JACKMAN',               movie: 'Logan' },
  { num: 10, actor: 'BEN STILLER',                movie: 'Zoolander' },
  { num: 11, actor: 'LINDSAY LOHAN',              movie: 'Mean Girls' },
  { num: 12, actor: 'LEONARDO DICAPRIO',          movie: 'Titanic' },
  { num: 13, actor: 'JARED LETO',                 movie: 'Morbius' },
  { num: 14, actor: 'TOM HOLLAND',                movie: 'Uncharted' },
  { num: 15, actor: 'JOHNNY DEPP',                movie: 'Pirates of the Caribbean: The Curse of the Black Pearl' },
  { num: 16, actor: 'LANA CONDOR',                movie: "To All the Boys I've Loved Before" },
  { num: 17, actor: 'DWAYNE "THE ROCK" JOHNSON',  movie: 'Jumanji: Welcome to the Jungle' },
  { num: 18, actor: 'ZENDAYA',                    movie: 'Spider-Man: No Way Home' },
  { num: 19, actor: 'ANNE HATHAWAY',              movie: 'The Princess Diaries' },
  { num: 20, actor: 'TOM HANKS',                  movie: 'Catch Me If You Can' },
  { num: 21, actor: 'RYAN REYNOLDS',              movie: 'Red Notice' },
  { num: 22, actor: 'JENNIFER GARNER',            movie: 'The Adam Project' },
  { num: 23, actor: 'JACK BLACK',                 movie: 'School of Rock' },
  { num: 24, actor: 'JACOB ELORDI',               movie: 'The Kissing Booth' },
  { num: 25, actor: 'NICOLAS CAGE',               movie: 'National Treasure' },
  { num: 26, actor: 'TARON EGERTON',              movie: 'Kingsman: The Secret Service' },
  { num: 27, actor: 'JENNA ORTEGA',               movie: 'Scream (2022)' },
  { num: 28, actor: 'ADAM DRIVER',                movie: 'Marriage Story' },
  { num: 29, actor: 'HEATH LEDGER',               movie: 'The Dark Knight' },
  { num: 30, actor: 'MILES TELLER',               movie: 'Whiplash' },
  { num: 31, actor: 'GWYNETH PALTROW',            movie: 'Iron Man' },
  { num: 32, actor: 'JACKIE CHAN',                movie: 'Rush Hour' },
  { num: 33, actor: 'CHRIS HEMSWORTH',            movie: 'Avengers: Endgame' },
  { num: 34, actor: 'EMMA WATSON',                movie: 'The Perks of Being a Wallflower' },
  { num: 35, actor: 'VIN DIESEL',                 movie: 'The Fast and the Furious' },
  { num: 36, actor: 'CHRISTIAN BALE',             movie: 'Batman Begins' },
  { num: 37, actor: 'JIM CARREY',                 movie: 'Ace Ventura: Pet Detective' },
  { num: 38, actor: 'DAVID CORENSWET',            movie: 'Superman (2025)' },
  { num: 39, actor: 'JEFF GOLDBLUM',              movie: 'Jurassic Park' },
  { num: 40, actor: 'ROBERT PATTINSON',           movie: 'Mickey 17' },
  { num: 41, actor: 'MARGOT ROBBIE',              movie: 'Barbie' },
  { num: 42, actor: 'RACHEL McADAMS',             movie: 'The Notebook' },
  { num: 43, actor: 'TOM CRUISE',                 movie: 'Mission: Impossible' },
  { num: 44, actor: 'DANIEL RADCLIFFE',           movie: "Harry Potter and the Philosopher's Stone" },
  { num: 45, actor: 'KRISTEN STEWART',            movie: 'Twilight' },
  { num: 46, actor: 'JENNIFER LAWRENCE',          movie: 'The Hunger Games' },
].map(c => ({ id: 'seed-' + c.num, image: null, ...c }));
